version: '3'
services:
  op_mysql:
    container_name: op_mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: osaamispankki
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  app:
    build: .
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: mvn clean spring-boot:run
    depends_on:
      - op_mysql
