FROM maven:3.5-jdk-8

# ENV MYSQL_DATABASE osaamispankki
# ENV MYSQL_ROOT_PASSWORD osaamispankki
# ENV MYSQL_USER user_osaamispankki

# COPY ./src/main/resources/sql-scrpits/ /docker-enterpoint-initdb.d/

# EXPOSE 3306

# docker run -d -p 3306:3306 --name=mysql-osaamispankki --env="MYSQL_ROOT_PASSWORD=123456" mysql
# docker exec -it mysql-server bash
# mysql -u root -p
